export const SAVE_TASK = 'save_task'
export const UPDATE_TASK_VALUE = 'update_task_value'
export const DELETE_TASK = 'delete_task'
export const TOGGLE_COMPLETE_TASK = 'toggle_complete_task'
export const FETCHED_TASK = 'fetched_task'
export const LOADING = 'loading'
